import * as fs from "node:fs";
import * as path from "node:path";
import { match } from "ts-pattern";
import type { DocGenerator, FileIR, Position, TokenInfo } from "../types";

/**
 * We turn the source code with Highlight Info into HTML
 * Only syntax highlighting is considered - hover and definition are ignored for now
 */
class HTMLGenerator implements DocGenerator {
	/**
	 * Convert position to character offset in source text
	 */
	private positionToOffset(text: string, pos: Position): number {
		const lines = text.split("\n");
		let offset = 0;

		for (let i = 0; i < pos.line; i++) {
			offset += lines[i].length + 1; // +1 for newline
		}

		return offset + pos.column;
	}

	/**
	 * Sort tokens by start position to ensure correct processing order
	 */
	private sortTokens(tokens: TokenInfo[]): TokenInfo[] {
		return tokens.sort((a, b) => {
			if (a.span.start.line !== b.span.start.line) {
				return a.span.start.line - b.span.start.line;
			}
			return a.span.start.column - b.span.start.column;
		});
	}

	/**
	 * Escape HTML special characters to prevent rendering issues
	 */
	private escapeHtml(text: string): string {
		return text
			.replace(/&/g, "&amp;")
			.replace(/</g, "&lt;")
			.replace(/>/g, "&gt;")
			.replace(/"/g, "&quot;")
			.replace(/'/g, "&#039;");
	}

	/**
	 * Extract highlight classes from token meta, ignore other types
	 */
	private extractHighlightClasses(meta: TokenInfo["meta"]): string[] {
		const classes: string[] = [];

		meta.forEach((m) => {
			match(m)
				.with({ type: "highlight" }, (m) => {
					classes.push(...m.highlightClasses);
				})
				.with({ type: "hover" }, () => {
					// Ignore hover info for now
				})
				.with({ type: "definition" }, () => {
					// Ignore definition info for now
				})
				.exhaustive();
		});

		return classes;
	}

	/**
	 * Generate HTML from FileIR and TokenInfo
	 */
	generate(fileIR: FileIR, info: TokenInfo[]): string {
		try {
			// Read source file content
			const sourcePath = path.resolve(fileIR.filePath);
			if (!fs.existsSync(sourcePath)) {
				throw new Error(`Source file not found: ${sourcePath}`);
			}

			const sourceContent = fs.readFileSync(sourcePath, "utf-8");

			// Filter and sort tokens that have highlight info
			const highlightTokens = info.filter(
				(token) => this.extractHighlightClasses(token.meta).length > 0,
			);
			const sortedTokens = this.sortTokens(highlightTokens);

			// Generate HTML with syntax highlighting
			const htmlContent = this.generateHighlightedHTML(
				sourceContent,
				sortedTokens,
			);

			return this.wrapInHTMLTemplate(fileIR, htmlContent);
		} catch (error) {
			throw new Error(
				`Failed to generate HTML for ${fileIR.filePath}: ${error}`,
			);
		}
	}

	/**
	 * Generate HTML with highlighted tokens, preserving all source text
	 */
	private generateHighlightedHTML(
		sourceContent: string,
		tokens: TokenInfo[],
	): string {
		if (tokens.length === 0) {
			// No highlight tokens, just escape and wrap in pre/code
			return `<pre><code>${this.escapeHtml(sourceContent)}</code></pre>`;
		}

		let result = "";
		let currentOffset = 0;

		// Process tokens in order
		for (const token of tokens) {
			const tokenStart = this.positionToOffset(
				sourceContent,
				token.span.start,
			);
			const tokenEnd = this.positionToOffset(
				sourceContent,
				token.span.end,
			);

			// Add text before token (unhighlighted but preserved)
			if (tokenStart > currentOffset) {
				const textBefore = sourceContent.slice(
					currentOffset,
					tokenStart,
				);
				result += this.escapeHtml(textBefore);
			}

			// Add highlighted token with CSS classes
			const tokenText = sourceContent.slice(tokenStart, tokenEnd);
			const classes = this.extractHighlightClasses(token.meta);

			if (classes.length > 0) {
				const classAttr = ` class="${classes.join(" ")}"`;
				result += `<span${classAttr}>${this.escapeHtml(tokenText)}</span>`;
			} else {
				// No highlight classes, just escape the text
				result += this.escapeHtml(tokenText);
			}

			currentOffset = tokenEnd;
		}

		// Add remaining text after last token
		if (currentOffset < sourceContent.length) {
			const remainingText = sourceContent.slice(currentOffset);
			result += this.escapeHtml(remainingText);
		}

		return `<pre><code>${result}</code></pre>`;
	}

	/**
	 * Wrap content in basic HTML template
	 */
	private wrapInHTMLTemplate(fileIR: FileIR, content: string): string {
		const fileName = path.basename(fileIR.filePath);
		return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${fileName} - Cire Documentation</title>
</head>
<body>
    <h1>${fileName}</h1>
    <p>Generated by Cire - Static Documentation Generator</p>
    <div>
        ${content}
    </div>
</body>
</html>`;
	}
}

export { HTMLGenerator };
export default HTMLGenerator;
